### ISSUE TITLE
Program Structure Diagram image is missing in production 

### ISSUE THREAD

**Issue by taboca** [FidelLimited/docs#79]
## Problem 

Fidel Docs programs page is missing an important diagram picture, an image file, in production. By the way, this image is properly available in this repository at https://github.com/FidelLimited/docs/blob/master/assets/images/programs_diagram_2020.png

Readme file: 

```
programs/README.md 
```

Section in the markdown

```
![Programs structure diagram](https://docs.fidel.uk/assets/images/programs_diagram_2020.png "Programs structure diagram")
```

## How to reproduce 

You can see the missing image in production or also via GitHub (since the images are hot links from production): 

* https://docs.fidel.uk/programs
* https://github.com/FidelLimited/docs/tree/master/programs

![Screen Shot 2020-04-03 at 18 27 58](https://user-images.githubusercontent.com/8658/78407556-7c2f8c80-75db-11ea-8caa-3dea91d0be9d.png)

**Comment by c0derabbit** [comment]
@taboca thanks for letting us know, we've just swapped that image and seem to have put it in the wrong place. We'll fix this early next week!
