### ISSUE TITLE
Fidel Docs does not allow hash tag links from outside documentation 

### ISSUE THREAD

**Issue by taboca** [FidelLimited/docs#83]
I a moving this contribution from my own repository, https://github.com/taboca/docs/issues/7, to this one. 

## Problem 

As a developer-writer, I tried to link to "https://docs.fidel.uk/programs#add-locations" from another article, but it seems like the initial page load system could not figure the URL hash and didn't jump to the section. 

### How to test 

Paste the following URL: 
```
https://docs.fidel.uk/programs#add-locations
```

### What to expect? 

The browser to jump to the right section. 

### What happens? 

The initial loading, which takes a bit of time, figures the "/program" component of the URL, and removes the #section part. 

## Hypothesis

Perhaps "jump to section" using URL#hash format was not implemented in the markdown-to-docs system.

**Comment by c0derabbit** [comment]
closing as we've moved the docs to fidel.uk/docs where hash is respected
