### ISSUE TITLE
Fidel Docs shows subtitle as markdown raw text (####) instead of being shown with larger font 

### ISSUE THREAD

**Issue by taboca** [FidelLimited/docs#85]
## Problem

![Screen Shot 2020-04-11 at 15 18 19](https://user-images.githubusercontent.com/8658/79051665-c3370680-7c07-11ea-9ad2-003c63533e32.png)

## Solution hypothesis

I didn't try the fix because I don't have on my end the docs generation framework. 

https://github.com/taboca/docs/commit/fecfdb46694eb8c16ededbe774f8ac2af4d573cb

**Comment by andrelias** [comment]
Fixed.
