### ISSUE TITLE
Fidel Docs may suggest that Brands are directly added to a Program 

### ISSUE THREAD

**Issue by taboca** [FidelLimited/docs#86]
*This feedback is based on a first reading experience, when I found Fidel Docs as part of an interview process; I decided to annotate some points— things I may perceived as ambiguous. Keep in mind that it's my own view and not exactly a problem in the documentation. * 

## at "Brands" https://docs.fidel.uk/brands 

"After creating an account and getting access to the dashboard, the next step is to create a test Brand (Merchant). This lets you create locations and add them to a Program so you can start tracking transactions."

### Notes of the first reading 

I incorrectly grasped a mental model that Brand was part of Program — I thought that the *them* had to do with the *Brands* not with *locations. So your english is right, but it was too abrupt to expect me to consume "locations" at that point in time too early in that document. 

![Screen Shot 2020-04-17 at 15 35 06](https://user-images.githubusercontent.com/8658/79602545-0b02d580-80c1-11ea-8e1c-f7d1dcc29bdf.png)

The following was a note that I made from the initial reading days: 

![Screen Shot 2020-04-17 at 15 33 17](https://user-images.githubusercontent.com/8658/79602413-ce36de80-80c0-11ea-83f1-5f40d6484609.png)

From that note I even claimed "So wait, how can I add a Brand to a Program if the program was not added. "

I may also have confirmed this mental model when I eventually saw the diagram with Brands under Program: 

![Screen Shot 2020-04-17 at 15 38 03](https://user-images.githubusercontent.com/8658/79602751-7482e400-80c1-11ea-9812-2aa4eba57d29.png)

## Feedback after playing with the dashboard and returning to Fidel Docs one week later

I patched my prior mental model with the understanding that: 

```
 Programs -> Locations (of Brands) and that Brands are shared
```

From a developer's perspective this aligned with the dashboard; and also aligned with the following statements from Docs:

* at Programs —  "A Program is a set of locations that uniquely represent an offline or online store where transactions from linked cards will be monitored. " https://docs.fidel.uk/programs#add-locations —

* At Programs —  The Program is the parent object of your card linked structure. Other objects such as Cards, Locations, Webhooks and Transactions will always be linked to a Program. Brands are shared across Programs.  https://docs.fidel.uk/programs#add-locations

## Reasoning 

I came to the conclusion that, for a developer audience, it would be correct to maintain the notion: 

```
 Programs -> Locations (of Brands) and that Brands are shared
```

And that the [diagram](https://github.com/FidelLimited/docs/blob/master/assets/images/programs_diagram_2020.png) may have influenced me to think differently. On the other hand I also understand from the diagram that Brands are *in*directly associated with Programs.

**Comment by andrelias** [comment]
Improved Brand documentation.
