### ISSUE TITLE
Fidel Docs sample tells nothing about secret key

### ISSUE THREAD

**Issue by taboca** [FidelLimited/docs#89]
_*This feedback is based on a first reading experience, when I found Fidel Docs as part of an interview process; I decided to annotate some points— things I may perceived as ambiguous. Keep in mind that it's my own view and not exactly a problem in the documentation. *_

## Problem 

Context — At Fidel Docs, specifically https://docs.fidel.uk/offers/create-offer the developer can see a sample. This sample was presented with a significant amount of information to help the developer to understand the parameter (brandId) passed and also payload parameters. 

Problem — Information was missing about the secret key. 

## Solution 
 
Later, when visiting the [API Reference Authentication](https://reference.fidel.uk/reference#authentication) section I have noticed a good explanation about the key differences. So perhaps it would be interesting to update the sample at Fidel Docs to point to the API Reference: 

### Patch 

https://github.com/taboca/docs/commit/5010ff22aa4d6b6ea49d54f2654d58abdb6a6fc1

#### Was 

![Screen Shot 2020-04-11 at 15 55 18](https://user-images.githubusercontent.com/8658/79052432-e1ebcc00-7c0c-11ea-8134-39bc30ada89b.png)

#### Suggestion

To ensure security, your secret API key should be passed as the element "fidel-key" in the HTTP header — check more about authentication and keys at [API Reference]. All the offer parameters should be formatted in JSON in the payload.

As required parameters, you need to set the `brandId`, an offer `name`, your `accountId` as the `publisherId` (get your accountId checking the raw objects in the Dashboard), a `startDate` at least three weeks from today, the type of offer between `amount` or `discount`, an offer `value`, and the `countryCode` where the offer will be available. The `value` is a percentage if the offer `type` is `discount` or a fixed amount in the local currency of the `countryCode` specified.

**Comment by andrelias** [comment]
Fixed
