### ISSUE TITLE
Fidel Docs ytpo "processand" -> process and 

### ISSUE THREAD

**Issue by taboca** [FidelLimited/docs#95]
## Problem 

Just a typo - at https://docs.fidel.uk/programs/add-locations search for "processand"

![Screen Shot 2020-04-17 at 17 02 38](https://user-images.githubusercontent.com/8658/79609521-46a39c80-80cd-11ea-8e24-6295f301d7c5.png)

**Comment by c0derabbit** [comment]
fixed.
